### PR TITLE
Out of (kernel) tree device trees

### PR DESCRIPTION
**Pull request by bradbishop**
Add plumbing and initial device trees for Palmetto/Barreleye.
Bump kernel version.

### CODE REVIEW

**Comment by jk-ozlabs** [comment]
Do we really want to do this? it'll mean we need to synchronise poky with the kernel for every new device added.

**Comment by bradbishop** [comment]
I think the vision is that we don't have any device trees in the kernel source.  Or, they can be there, but they are just for you guys to develop against - similar to what we are doing with defconfigs.  With that in mind is there still a sync needed?

**Comment by jk-ozlabs** [comment]
I'd disagree with that - the device tree is very tightly coupled with the kernel version (especially at the moment), and shouldn't affect things outside of the kernel.

Kernel .configs are a little different in that regard, as they're providing features that OpenBMC requires, and not just items that the kernel requires.

If we really do want to keep the device trees separate, we should do this once the drivers are all complete; it's just going to slow us down before that point.

**Comment by nkskjames** [comment]
so what are we doing?    i have an outstanding pull request in the kernel for this.  Do I close that?

**Comment by williamspatrick** [comment]
Merging for now. We can revert if there is disagreement after discussion but we need to get the dev trees in now.

**Comment by jk-ozlabs** [comment]
@williamspatrick : why do we need the dev trees separate now? The dts files, as you merged them, were the same as the kernel's, no?

**Pull request merged**
