### PR TITLE
Merge pull request #1 from openbmc/master

### PR DESCRIPTION
**Pull request by pangxueze**
update openbmc, pull master to my project

Please do not submit a Pull Request via github.  Our project makes use of
Gerrit for patch submission and review.  For more details please
see https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes-via-gerrit-server

### CODE REVIEW

**Comment by pangxueze** [comment]
update openbmc master to pangxueze personal branch

**Comment by pangxueze** [comment]
update openbmc master to pangxueze personal branch

**Comment by amboar** [comment]
Hi @pangxueze,

As noted in the pull-request template you've left in your initial comment, OpenBMC doesn't use pull-requests for patch submission. Instead we use a Gerrit instance at https://gerrit.openbmc-project.xyz/. Please direct your patches there.

**Comment by edtanous** [comment]
> OpenBMC doesn't use pull-requests for patch submission

What amboar said, please submit your patches to gerrit.  Closing.

**Pull request closed without merging**
