### PR TITLE
Add autostart policy for these 17 services of the openbmc repo.

### PR DESCRIPTION
**Pull request by williamli80**
Add autostart policy for these 17 services of the openbmc repo.

Signed-off-by: Nan Li bjlinan@cn.ibm.com

---
This change is [Review on Reviewable](https://reviewable.io/reviews/openbmc/openbmc/149)

### CODE REVIEW

**Comment by williamspatrick** [comment]
ok to test

**Comment by mkumatag** [comment]
what is the update? when are we merging this?

**Comment by williamspatrick** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/openbmc/149#-KCNt1SyfuUFyIHMfzHx:-KCNt1SyfuUFyIHMfzHy:-580174436) (no related file):*
Need a rebase and need it to pass Jenkins test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/149)*

**Comment by csmart** [comment]
This seems to break barreleye https://openpower.xyz/job/openbmc-build-pull-request/122/distro=ubuntu,target=barreleye/console

```
08:08:57 9: squashfs-tools-native-4.3+gitrAUTOINC+9c1db6d13a-r0 do_populate_lic (pid 43437)
08:08:57 ERROR: Command Error: exit status: 1  Output:
08:08:57 Applying patch skeleton.patch
08:08:57 patching file skeleton.service
08:08:57 Hunk #1 FAILED at 2.
08:08:57 1 out of 1 hunk FAILED -- rejects in file skeleton.service
08:08:57 Patch skeleton.patch does not apply (enforce with -f)
08:08:57 Currently 10 running tasks (696 of 2139):
08:08:57 0: gcc-source-4.9.3-4.9.3-r0 do_unpack (pid 239)
08:08:57 1: linux-obmc-4.3+gitAUTOINC+908a99951b-r0 do_unpack (pid 1284)
08:08:57 2: m4-native-1.4.17-r0 do_configure (pid 3919)
08:08:57 3: u-boot-v2013.07+gitAUTOINC+4b44678c11-r0 do_unpack (pid 34521)
08:08:57 4: u-boot-fw-utils-v2013.07+gitAUTOINC+4b44678c11-r0 do_fetch (pid 35019)
08:08:57 5: e2fsprogs-native-1.42.9-r0 do_patch (pid 38119)
08:08:57 6: lz4-native-131+gitAUTOINC+d86dc91677-r0 do_unpack (pid 42587)
08:08:57 7: python-smartpm-native-1.5+gitAUTOINC+407a7eca76-r0 do_patch (pid 42663)
08:08:57 8: skeleton-1.0-r1 do_patch (pid 43194)
08:08:57 9: squashfs-tools-native-4.3+gitrAUTOINC+9c1db6d13a-r0 do_populate_lic (pid 43437)
08:08:57 ERROR: Function failed: patch_do_patch
08:08:57 Currently 10 running tasks (696 of 2139):
08:08:57 0: gcc-source-4.9.3-4.9.3-r0 do_unpack (pid 239)
08:08:57 1: linux-obmc-4.3+gitAUTOINC+908a99951b-r0 do_unpack (pid 1284)
08:08:57 2: m4-native-1.4.17-r0 do_configure (pid 3919)
08:08:57 3: u-boot-v2013.07+gitAUTOINC+4b44678c11-r0 do_unpack (pid 34521)
08:08:57 4: u-boot-fw-utils-v2013.07+gitAUTOINC+4b44678c11-r0 do_fetch (pid 35019)
08:08:57 5: e2fsprogs-native-1.42.9-r0 do_patch (pid 38119)
08:08:57 6: lz4-native-131+gitAUTOINC+d86dc91677-r0 do_unpack (pid 42587)
08:08:57 7: python-smartpm-native-1.5+gitAUTOINC+407a7eca76-r0 do_patch (pid 42663)
08:08:57 8: skeleton-1.0-r1 do_patch (pid 43194)
08:08:57 9: squashfs-tools-native-4.3+gitrAUTOINC+9c1db6d13a-r0 do_populate_lic (pid 43437)
08:08:57 ERROR: Logfile of failure stored in: /var/lib/jenkins/workspace/openbmc-build-pull-request/distro/ubuntu/target/barreleye/openbmc/build/tmp/work/armv5e-openbmc-linux-gnueabi/skeleton/1.0-r1/temp/log.do_patch.43194
08:08:57 Currently 9 running tasks (696 of 2139):
08:08:57 0: gcc-source-4.9.3-4.9.3-r0 do_unpack (pid 239)
08:08:57 1: linux-obmc-4.3+gitAUTOINC+908a99951b-r0 do_unpack (pid 1284)
08:08:57 2: m4-native-1.4.17-r0 do_configure (pid 3919)
08:08:57 3: u-boot-v2013.07+gitAUTOINC+4b44678c11-r0 do_unpack (pid 34521)
08:08:57 4: u-boot-fw-utils-v2013.07+gitAUTOINC+4b44678c11-r0 do_fetch (pid 35019)
08:08:57 5: e2fsprogs-native-1.42.9-r0 do_patch (pid 38119)
08:08:57 6: lz4-native-131+gitAUTOINC+d86dc91677-r0 do_unpack (pid 42587)
08:08:57 7: python-smartpm-native-1.5+gitAUTOINC+407a7eca76-r0 do_patch (pid 42663)
08:08:57 8: squashfs-tools-native-4.3+gitrAUTOINC+9c1db6d13a-r0 do_populate_lic (pid 43437)
08:08:57 ERROR: Task 1233 (/var/lib/jenkins/workspace/openbmc-build-pull-request/distro/ubuntu/target/barreleye/openbmc/meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb, do_patch) failed with exit code '1'
```

**Comment by csmart** [comment]
Probably just needs a rebase on top of master...

**Comment by williamli80** [comment]
I remember that this story is deferred or cancelled?
Rebase done, but the build output is like :
06:22:30 ERROR: Command Error: exit status: 1  Output:
06:22:30 Applying patch skeleton.patch
06:22:30 patching file skeleton.service
06:22:30 Hunk #1 FAILED at 2.
06:22:30 1 out of 1 hunk FAILED -- rejects in file skeleton.service
06:22:30 Patch skeleton.patch does not apply (enforce with -f)

**Comment by williamli80** [comment]
Hi Chris Smart and Patric Williams,
I did a rebase, but it also cannot pass jenkins test. A patch failed. I 
don't know why.


Regards,

William Li ( Li Nan, ?? ) 

Firmware Engineering Professional
OpenPower AE Team | IBM System & Technology Lab
Mobile: +86-186-1081 6605, +86-138-1188 5954

Beijing, China

**Comment by csmart** [comment]
@williamli80 thanks for the rebase @jenkins-openbmc retest this please

**Comment by csmart** [comment]
@williamli80 the problem is there's a patch that gets applied on skeleton.service which changes it from Palmetto to Barreleye.

You've changed this file too, so the patch fails.

You need to change the patch also, so that it can be applied successfully.

The patch is located here:
meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-phosphor/skeleton/skeleton/skeleton.patch

And you need to change it to something like:

```
--- a/skeleton.service	2015-10-28 07:47:55.337712001 -0500
+++ b/skeleton.service	2015-10-28 07:34:05.277712001 -0500
@@ -3,7 +3,7 @@
 Description=Temp placeholder for skeleton function
 
 [Service]
 Restart=always
-ExecStart=/usr/sbin/system_manager.py Palmetto
+ExecStart=/usr/sbin/system_manager.py Barreleye
 
 [Install]
 WantedBy=multi-user.target
```

**Comment by csmart** [comment]
OK, this looks good now, thanks @williamli80

**Comment by anoo1** [comment]
@williamli80 Could you do a rebase once more? We'll merge sooner this time :)

**Comment by williamli80** [comment]
Hi,  rebased it. Please review.

**Comment by anoo1** [comment]
:lgtm:

<details><summary><i>Previously, williamli80 (William Li ( Nan Li, 李楠)) wrote…</i></summary>
> Hi,  rebased it. Please review.</details>


---

Reviewed 14 of 17 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/149#-:-KHzJQOJr7Y_EGjERoCj:1417088721)*

**Comment by williamspatrick** [comment]
merged manually.

**Comment by anoo1** [comment]
Merged with d092160b0e9d325c066a8d0f3dfc5f8a3b54506f

**Pull request closed without merging**
