### PR TITLE
Add note for avoiding libsdl dependency when building

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by shenki** [comment]
Can we please merge this?

**Comment by williamspatrick** [comment]
Is there a reason why we don't just update the conf templates or the distro files to do this globally?  These comments feel a little without context to me to place them in the global readme file.

**Comment by shenki** [comment]
Ok, we can do that instead.

This is something that independently three of us hit and wasted time solving, hence my desire to have it prominent on the front page of the repository.

**Comment by williamspatrick** [comment]
I entirely misread what this was about. Building on vs building for. I thought this was just an attempt to make it build faster. 

So you are running into a problem building when it is on a headless system?  Or just running?  Does adding 'nodisplay' to runqemu solve this on its own?

**Comment by shenki** [comment]
Yeah, we have a big machine we use for building stuff and it doesn't have X installed, so a few of us hit this.

In general I run qemu with nodisplay as I find it easier to use, but that's a separate concern.

**Pull request closed without merging**
