### PR TITLE
initial ast2500 stubs

### PR DESCRIPTION
**Pull request by bradbishop**
This patchset consists of a number of cleanup things in prep for a new ast2500 bsp layer, a new ast2500 bsp layer, and a layer for the ast2500 evaluation board.

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc/312)

### CODE REVIEW

**Comment by kc8apf** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 9 of 9 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 5 of 5 files at r9, 7 of 7 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[meta-openbmc-bsp/meta-aspeed/meta-ast2400/conf/machine/include/ast2400.inc, line 6 \[r5\]](https://reviewable.io:443/reviews/openbmc/openbmc/312#-KJbBAO_JrcusINsPFJO:-KJbBAO_JrcusINsPFJP:-795903050) ([raw file](https://github.com/openbmc/openbmc/blob/d183325881a020856caefc99b09c9258a39db61b/meta-openbmc-bsp/meta-aspeed/meta-ast2400/conf/machine/include/ast2400.inc#L6)):*
> ```SourcePawn
> 
> PREFERRED_PROVIDER_virtual/kernel ?= "linux-obmc"
> PREFERRED_VERSION_linux-obmc ?= "4.4+gitAUTOINC+6717e8fec2"
> ```

Does this need the full PV?  Really this is only trying to specify the linux-obmc_4.4 recipe, not the specific commit that happens to track.

---

*[meta-openbmc-bsp/meta-aspeed/meta-ast2500/conf/machine/include/ast2500.inc, line 14 \[r9\]](https://reviewable.io:443/reviews/openbmc/openbmc/312#-KJbCxVa-Hz4B5IDGolN:-KJbCxVa-Hz4B5IDGolO:1473435146) ([raw file](https://github.com/openbmc/openbmc/blob/4b478c73b4765d8152318aee024e8365a866ac75/meta-openbmc-bsp/meta-aspeed/meta-ast2500/conf/machine/include/ast2500.inc#L14)):*
> ```SourcePawn
> INITRD_IMAGE_LOADADDRESS = "0x80800000"
> 
> require conf/machine/include/tune-arm1136jf-s.inc
> ```

AST2500 is a ARM1176JZFS w/o vFPU.  The arm1176 tune includes I've seen assume vFPU is present.  I've been using the following instead:

DEFAULTTUNE = "armv6-novfp"
require conf/machine/include/arm/arch-armv6.inc

---

*[meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.6.bb, line 3 \[r7\]](https://reviewable.io:443/reviews/openbmc/openbmc/312#-KJbC9YEQ-nYAY9DQ5_5:-KJbC9YEQ-nYAY9DQ5_6:-881955843) ([raw file](https://github.com/openbmc/openbmc/blob/08a8443e9ef5db03725bb7da83eda4dda300e6dc/meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.6.bb#L3)):*
> ```BlitzBasic
> KBRANCH ?= "dev-4.6"
> LINUX_VERSION ?= "4.6"
> SRCREV="e377df455809d87488eed132b41583ead909f58a"
> ```

Use a tag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/312)*

**Comment by bradbishop** [comment]
Thanks for the review Rick.

On Mon, 2016-06-06 at 12:43 -0700, Rick Altherr wrote:
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 9
> of 9 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files
> at r7, 1 of 1 files at r8, 5 of 5 files at r9, 7 of 7 files at r10.
> Review status: all files reviewed at latest revision, 3 unresolved
> discussions, some commit checks failed.
> 
> 
> ______________________________________________________________________
> 
> meta-openbmc-bsp/meta-aspeed/meta-ast2400/conf/machine/include/ast2400.inc, line 6 [r5] (raw file):
> 
>         PREFERRED_PROVIDER_virtual/kernel ?= "linux-obmc"
>         PREFERRED_VERSION_linux-obmc ?= "4.4+gitAUTOINC+6717e8fec2"
> 
> Does this need the full PV? Really this is only trying to specify the
> linux-obmc_4.4 recipe, not the specific commit that happens to track.
> 

Yes, but only because 4.4+gitAUTOINC+sha is what the package version is
being set to.  We could certainly explore having a more concise version.
> 
> ______________________________________________________________________
> 
> meta-openbmc-bsp/meta-aspeed/meta-ast2500/conf/machine/include/ast2500.inc, line 14 [r9] (raw file):
> 
>         INITRD_IMAGE_LOADADDRESS = "0x80800000"
>         
>         require conf/machine/include/tune-arm1136jf-s.inc
> 
> AST2500 is a ARM1176JZFS w/o vFPU. The arm1176 tune includes I've seen
> assume vFPU is present. I've been using the following instead:
> 
> DEFAULTTUNE = "armv6-novfp"
> require conf/machine/include/arm/arch-armv6.inc
> 

Awesome!  Thx for that.  Will certainly incorporate this.  And
yeah...discovered today around the same time I read your note that
busybox is probably using floating point instructions and this tune
didn't work so hot.
> 
> ______________________________________________________________________
> 
> meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.6.bb, line 3
> [r7] (raw file):
> 
>         KBRANCH ?= "dev-4.6"
>         LINUX_VERSION ?= "4.6"
>         SRCREV="e377df455809d87488eed132b41583ead909f58a"
> 
> Use a tag
> 

Will do...as soon as Joel makes one for me.

**Comment by kc8apf** [comment]
I hacked on your commits today and got a full image to build.  Check out
the ast2500 branch of kc8apf/openbmc.  It was mostly trivial fixes and
u-boot recipes.

**Comment by kc8apf** [comment]
Reviewed 1 of 9 files at r4, 1 of 1 files at r12, 3 of 3 files at r13, 8 of 9 files at r14, 2 of 3 files at r15, 1 of 1 files at r16, 1 of 1 files at r19, 11 of 11 files at r20, 7 of 7 files at r21.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/312)*

**Comment by kc8apf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[meta-openbmc-bsp/meta-aspeed/meta-ast2400/conf/machine/include/ast2400.inc, line 6 \[r5\]](https://reviewable.io:443/reviews/openbmc/openbmc/312#-KJbBAO_JrcusINsPFJO:-KJm_-PYzpBXZ6q3N0cf:49025773) ([raw file](https://github.com/openbmc/openbmc/blob/d183325881a020856caefc99b09c9258a39db61b/meta-openbmc-bsp/meta-aspeed/meta-ast2400/conf/machine/include/ast2400.inc#L6)):*
<details><summary><i>Previously, kc8apf (Rick Altherr) wrote…</i></summary>
> Does this need the full PV?  Really this is only trying to specify the linux-obmc_4.4 recipe, not the specific commit that happens to track.
</details>
LGTM
Fixed in later revision

---

*[meta-openbmc-bsp/meta-aspeed/meta-ast2500/conf/machine/include/ast2500.inc, line 14 \[r9\]](https://reviewable.io:443/reviews/openbmc/openbmc/312#-KJbCxVa-Hz4B5IDGolN:-KJm_6m4iwY_RmyBdirt:49025773) ([raw file](https://github.com/openbmc/openbmc/blob/4b478c73b4765d8152318aee024e8365a866ac75/meta-openbmc-bsp/meta-aspeed/meta-ast2500/conf/machine/include/ast2500.inc#L14)):*
<details><summary><i>Previously, kc8apf (Rick Altherr) wrote…</i></summary>
> AST2500 is a ARM1176JZFS w/o vFPU.  The arm1176 tune includes I've seen assume vFPU is present.  I've been using the following instead:
> 
> DEFAULTTUNE = "armv6-novfp"
> require conf/machine/include/arm/arch-armv6.inc
</details>
LGTM
Fixed in later revision

---

*[meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.6.bb, line 3 \[r7\]](https://reviewable.io:443/reviews/openbmc/openbmc/312#-KJbC9YEQ-nYAY9DQ5_5:-KJm_9vGCORviGPWO6tP:-1301386573) ([raw file](https://github.com/openbmc/openbmc/blob/08a8443e9ef5db03725bb7da83eda4dda300e6dc/meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.6.bb#L3)):*
<details><summary><i>Previously, kc8apf (Rick Altherr) wrote…</i></summary>
> Use a tag
</details>
OK
Will be changed in follow up

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/312)*

**Comment by kc8apf** [comment]
Reviewed 1 of 9 files at r4, 1 of 9 files at r14, 1 of 1 files at r23, 3 of 3 files at r24, 6 of 6 files at r25, 2 of 3 files at r26, 1 of 1 files at r27, 1 of 1 files at r30, 11 of 11 files at r31, 7 of 7 files at r32.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/312)*

**Pull request merged**
