### PR TITLE
Bump IPMI, networkd, REST, and skeleton versions

### PR DESCRIPTION
**Pull request by anoo1**
Pick up:
Fix FRU VPD error messages
Add REST interface to update BMC via local file
Add Barreleye motherboard VPD to the inventory
Handle parallel IPMI SEL reservation requests
Add support to stream the journald log to a remote syslog

Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc/302)

### CODE REVIEW

**Comment by causten** [comment]
:lgtm:

<details><summary><i>Previously, anoo1 wrote…</i></summary>
> #### Bump IPMI, networkd, REST, and skeleton versions
> 
> Pick up:
> 
> Fix FRU VPD error messages
> 
> Add REST interface to update BMC via local file
> 
> Add Barreleye motherboard VPD to the inventory
> 
> Handle parallel IPMI SEL reservation requests
> 
> Add support to stream the journald log to a remote syslog
> 
> 
> 
> Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
> 
> 
> 
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/302#-:-KI_1Xt_FxtkbldQ4UvX:1417088721)*

**Comment by johnhcwang** [comment]
Hi @anoo1 , may I know the detail about "Add support to stream the journald log to a remote syslog"?
How do we enable this feature?
It seems helpful to debug the issue that need the long reproduce time.

**Comment by anoo1** [comment]
Hi @johnhcwang , here is the link to the documentation: https://github.com/openbmc/docs/blob/master/rfc-obmc-service-iface.md
Let us know if you have any questions.

**Comment by causten** [comment]
:lgtm:

<details><summary><i>Previously, anoo1 wrote…</i></summary>
> Hi @johnhcwang , here is the link to the documentation: https://github.com/openbmc/docs/blob/master/rfc-obmc-service-iface.md
> 
> Let us know if you have any questions.
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/openbmc/302#-:-KJDgu5U4qH8GEskCHUN:1417088721)*

**Comment by anoo1** [comment]
Committed with 03f51f5489813391c066bb62a5aa1e9eb06e658d

**Pull request closed without merging**
