### PR TITLE
meta-phosphor: Move to openbmc-20160321-1

### PR DESCRIPTION
**Pull request by shenki**
We are now on a 4.4 based kernel

 - Fix i2c_smbus_read_block_data error in our i2c bus driver
 - Includes many JFFS2 fixes identified by Milton:
    * Fix directory hardlinks from deleted directories
    * Revert "jffs2: Fix lock acquisition order bug in jffs2_write_begin"
    * jffs2: Fix page lock / f->sem deadlock
    * jffs2: reduce the breakage on recovery from halfway failed rename()
 - Remove our in-tree adm1275 driver in favour of the upstream one,
   which was cherry picked from 4.6-rc1
 - Squishes down most of the fixes that were found in the 4.3
   development effort into the commit that added the driver. This is
   part of the work in preparing for upstreaming Aspeed kernel support.

Signed-off-by: Joel Stanley <joel@jms.id.au>

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc/212)

### CODE REVIEW

**Comment by adamliyi** [comment]
The upstream adm1275 (adm1278) driver cannot work on Barreleye. There is no way to change the Sense Resistor value.

As described in:
https://github.com/adamliyi/openbmc/blob/adm1278_0313/meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-kernel/linux/linux-obmc/readme_adm1278.txt
```
5.2) According to adm1278 datasheet, there is a sense resistor used to measure power and current. The resistor will affect conversion between
adm1278 register value to real-world value for current and power. The default resistor value is 250 microohms.
When build the adm1275 driver as kernel module, we can set this resistor value by:

# insmod adm1275.ko r_sense=500

When the driver is built into kernel, in kernel boot option, add:

adm1275.r_sense=500

This will set the 'sense resistor' to 500 micro-ohms.
```

**Comment by shenki** [comment]
Hey Adam,

You're correct; the upstream driver lacks support for anything like this. They explain why in the documentation (https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface):

 > Actual voltage depends on the scaling resistors on the motherboard, as
 > recommended in the chip datasheet. This varies by chip and by motherboard.
 > Because of this variation, values are generally NOT scaled by the chip driver,
 > and must be done by the application. However, some drivers (notably lm87 and
 > via686a) do scale, because of internal resistors built into a chip. These
 > drivers will output the actual voltage. Rule of thumb: drivers should report
 > the voltage values at the "pins" of the chip.

I agree that we cannot hardcode the values, and your method of using a device parameter is a bit clumsy. A better choice would be to encode this information in the motherboard-specific device tree.

It also lacks support for device tree based probing, which we will need to add.

I'll start a discussion with upstream about doing this.

**Comment by williamspatrick** [comment]
We need to hold off merging until the adm1278 issue is resolved.

@shenki - Should we undo your backport and removal of the adm1278 patch for the time being?

**Comment by mdmillerii** [comment]
We can't merge with a broken jffs2 / ast flash driver combination.  The pr_warn on src/jffs2/scan.c line 671 is triggering and the fs returns EIO with these additional patches applied: mdmillerii@94b66f3ebd39927c106d5513f6b5dd9d4cf1862b

**Comment by shenki** [comment]
@williamspatrick With the patches linked above your comment (https://github.com/openbmc/linux/issues/64), we can use the upstream driver. I would prefer this, as it is the long term solution. Once @adamliyi has reviewed the changes I will update this PR with a new tag.

Obviously we're also waiting on @mdmillerii to debug his JFFS2 issue as well.

**Comment by adamliyi** [comment]
If we agree to put the sense resistor value as a "scale factor" in user space, I think we can just use the upstream adm1278 driver (with device tree enabled).

**Comment by shenki** [comment]
This new tag has @mdmillerii's fix for the JFFS2 issue we were seeing, and the device tree enabled adm1278. 

@adamliyi do you want me to drop the patch that adds device tree scale factor to the adm1278 and do it in userspace? If so, I will make that change and push a new tag.

Otherwise, this should be good to go. Tested on a Barreleye.

**Pull request merged**
