### PR TITLE
Add support for gevent package.

### PR DESCRIPTION
**Pull request by shgoupf**
Gevent package is required by latest obmc-rest for streaming.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/openbmc/openbmc/161)

### CODE REVIEW

**Comment by williamspatrick** [comment]
ok to test

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/161#-:-KCNuZYd2cX4JTM_liVA:1131371416)*

**Comment by williamspatrick** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNwAEsUDd1rasT43rY:-KCNwAEtbJxcx5W8Sjle:2016396590) (no related file):*
There are a lot of new python recipes here.  Did you write these all yourself or is there another layer these were picked up from?  Should we be contributing these upstream to Yocto / OE somewhere?

---

*[meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb, line 1 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNurSbPwReCIFAtYz2:-KCNurSbPwReCIFAtYz3:-1680306278) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb#L1)):*
Why do we need the CA bundle?

---

*[meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb, line 11 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNvOrU3rsp_gjS-LY6:-KCNvOrVAb-F1lt8A7x2:270302137) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb#L11)):*
The comment in the description seems to imply that libevent should be an RDEPEND (runtime dependency).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/161)*

**Comment by shgoupf** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNwAEsUDd1rasT43rY:-KCO-VU6Mnpry-VwR1q7:-937797244) (no related file):*
I picked most of them from other opensource layers available in the internet. So I believe there is no need to contribute them to yocto.

---

*[meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb, line 1 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNurSbPwReCIFAtYz2:-KCO-x2jGBWMnlobj1ng:1204188946) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb#L1)):*
This receipt file is got from opensource project in the internet so I didn't check the descriptions before. I don't think the CA bundle matters here.

---

*[meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb, line 11 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNvOrU3rsp_gjS-LY6:-KCO0UZx8lcsxgBV-uH0:-897329768) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb#L11)):*
Yes I believe gevent should be runtime dependency. If there are concerns from your side for this, let me know.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/161)*

**Comment by williamspatrick** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNwAEsUDd1rasT43rY:-KCO1_E9gbwjQl8nmUs0:1310358076) (no related file):*
We should probably consider using that layer then.  Having you copy files without attribution is a copyright problem.

Can you identify what layers you got these from?  We can discuss if we should pick up the whole layer or how to proceed.

---

*[meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb, line 1 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNurSbPwReCIFAtYz2:-KCO1t7hE5JV_7xwSEoT:-34588535) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb#L1)):*
Can you explain why we would need to verify anything?  I'm not understanding why we need this package.

---

*[meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb, line 11 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNvOrU3rsp_gjS-LY6:-KCO2EFp1skIx53ChEoM:2013775573) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb#L11)):*
My concern is that I don't think libevent will be installed if you just have it as a DEPENDS and not an RDEPENDS.  Maybe I am remembering wrong.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/161)*

**Comment by shgoupf** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNwAEsUDd1rasT43rY:-KCO6gB-W9raZxy62pBc:-2073978267) (no related file):*
These receipts are got from, for example, 
http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/tree/recipes-devtools/python/python-gevent_1.0.1.bb?h=master
and I made changes such as the revision number, etc.

---

*[meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb, line 1 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNurSbPwReCIFAtYz2:-KCO6zYN2sLiyYH0sXFd:1070927044) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-certifi_14.05.14.bb#L1)):*
I remember this package is required by gevent's wgsi https server.

---

*[meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb, line 11 \[r1\]](https://reviewable.io:443/reviews/openbmc/openbmc/161#-KCNvOrU3rsp_gjS-LY6:-KCO7GkYX_Ejexx7pLD7:-744753904) ([raw file](https://github.com/openbmc/openbmc/blob/a192b2139bda302804b6633da7a8fbb985e8a04a/meta-phosphor/common/recipes-devtools/python/python-gevent_1.1rc3.bb#L11)):*
I have tested this with my another bundle which requires gevent to work. So I believe this will be installed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/161)*

**Comment by williamspatrick** [comment]
@bradbishop - Please give feedback too.

**Comment by williamspatrick** [comment]
I think we decided to do this another way.

**Pull request closed without merging**
