### PR TITLE
Yocto cleanup

### PR DESCRIPTION
**Pull request by williamspatrick**
Commits were incorrectly applied into the yocto-poky tree.  This tree is intended to be a mirror of the original yocto/poky repository.  Move the content out of the yocto-poky tree and into meta-phosphor.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/openbmc/openbmc/203)

### CODE REVIEW

**Comment by williamspatrick** [comment]
retest this please

**Comment by csmart** [comment]
@jenkins-openbmc retest this please

**Comment by bradbishop** [comment]
Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/203)*

**Comment by mdmillerii** [comment]
So diffing yocko-poky betwen this 5e95bb193441d205782fd9d0b50d0fc1a8fced20 and 3445365503e1e4d5601acf7c05609cc9673ec414 I still see changes to siteinfo.bbclass, 
to the qemu recipie, and the updated dropbear recipe.

Do you plan to fix these too?
At least note the remaining work.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/203#-:-KCRSD06u8vbbVL_SWGe:-822569252)*

**Comment by williamspatrick** [comment]
I've got these under control too... planning to have another pull request to update yocto-poky.

* I pushed siteinfo.bbclass upstream.
* qemu recipe is no longer needed due to udev update.
* dropbear is updated in latest yocto.
* glibc patch I'm still tracking down, but I think is covered by support in glibc 2.23.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/openbmc/203#-:-KCRWNdfEiJ1XVoSfOML:710334740)*

**Pull request merged**
