### PR TITLE
add i2c-occ to barreleye and palmetto device table

### PR DESCRIPTION
**Pull request by adamliyi**
So i2c-occ driver can be initialized and read sensor data from OCC.

### CODE REVIEW

**Comment by csmart** [comment]
test this please

**Comment by csmart** [comment]
ok to test

**Comment by adamliyi** [comment]
Add occ to both palmetto and Barreleye device table.

**Comment by csmart** [comment]
@jenkins-openbmc test this please

**Comment by csmart** [comment]
@jenkins-openbmc add to whitelist

**Comment by csmart** [comment]
@jenkins-openbmc ok to test

**Comment by csmart** [comment]
@jenkins retest this please

**Comment by csmart** [comment]
@jenkins-openbmc retest this please

**Pull request closed without merging**
