### PR TITLE
Add palmetto target to runqemu, with networking

### PR DESCRIPTION
**Pull request by amboar**
The patches modelling a bare-bones AST2400 in QEMU have been merged into
master for the upcoming 2.6 release. Attached is an attempt at integrating the
necessary bits into openbmc so we can `bitbake obmc-phosphor-image` then
`runqemu palmetto` to boot the BMC kernel and some representation of the
userspace.

This revision includes support for slirp and tun/tap networking: The machine
will come up at either 10.0.2.15 or 192.168.7.2 respectively. Note that the
network controller modelled is a Cadence GEM and not the ftgmac device, which
is a little inaccurate but means we can have networking sooner rather than
later.

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc/230)

### CODE REVIEW

**Comment by amboar** [comment]
@jenkins-openbmc retest this please

**Comment by amboar** [comment]
Looks like tun/tap functionality is broken, will push a fix shortly.

**Comment by shenki** [comment]
@amboar Given the discovery of the patches for the ftgmac100 model, I'd prefer not to merge this series with the Cadence device.

I've integrated the ftgmac100 device here. Can you try it instead?

 https://github.com/shenki/qemu/tree/ftgmac100

**Comment by amboar** [comment]
@shenki yeah, that would be my preference too, but I was taking longer than I hoped to get around to looking at the ftgmac device so I figured I should submit what I had (which I thought was working but apparently not).

**Comment by williamspatrick** [comment]
Is this still RFC stage?  I'd like to see no modifications of the yocto tree if we can help it and limited duplication from it.  Should favor bbappend instead of copying .inc files or .bb files wholesale.

**Comment by amboar** [comment]
@shenki seems like the ftgmac100 qemu model has some severe issues surrounding the ISR register. I don't know exactly where the problem lies but the consequence is either the kernel boots and the MAC doesn't function, or we get memory allocation failures dequeuing rx'ed packets and we fail to boot as the driver has allocated all available GFP_ATOMIC memory.

**Comment by amboar** [comment]
@williamspatrick ah yes, your previous comments there slipped through the cracks. I'll take a look at cleaning things up today. Sorry about that!

**Comment by amboar** [comment]
@williamspatrick taking a closer look at trying to clean things up, a few bits of reasoning for the current approach:

* The `yocto-poky/scripts` directory is "special" in that `oe-init-build-env` adjusts `PATH` such that it's the first directory searched.
* the symlink target for `oe-init-build-env` lives in `yocto-poky/`, so is similarly undesirable for modification (i.e. put our own scripts directory on the path before `yocto-poky/scripts`)
   * Maybe this is a less bad approach though as the patches in `yocto-poky/` are smaller, though then we end up "duplicating" `runqemu` and `runqemu-internal` to add palmetto-bmc support
* Using `bbappend` to modify the `qemu_2.4.0.bb` to build something that very much isn't qemu 2.4.0 (i.e. much closer to 2.6.0) doesn't sit nicely with me
   * Do I bother to backport the ast2400 patches to qemu 2.4.0?
* `qemu.inc` isn't a straight copy, I've removed some configuration elements that cause modern qemus to fail to build. Though maybe my approach is hacky? I just deleted bits until it worked.
* `qemu-targets.inc` _is_ an unchanged copy - I'll see if I can eliminate it.

Given that, any thoughts on a way forward?

**Comment by causten** [comment]
I've tested this version of qemu/palmetto and it 
Is there a "how do I quit"?  
Does this work for barreleye too?

**Comment by amboar** [comment]
@causten thanks for testing. As for quitting, the trick is to switch to the monitor and then issue 'quit'. You can switch to monitor mode with `ctrl-a c`. I'll take a quick look at what needs to happen to kill qemu as well.

I haven't done anything to explicitly support barreleye. Given the sparsity of the qemu model you could likely reuse the palmetto-bmc qemu machine, which in turn just means some changes to `runqemu{,-internal}` to add 'barreleye' where 'palmetto' is currently mentioned.

**Comment by amboar** [comment]
@causten @shenki mentioned the watchdog is used to reset the BMC, in which case we'd need to add a few bits to qemu to make it exit, but it seems like it's possible to hack something together.

For now though hopefully the "switch to monitor and quit" approach is usable enough.

**Comment by amboar** [comment]
Closing this and starting a conversation with upstream about better extension of the runqemu scripts.

**Pull request closed without merging**
